# Generated by Django 5.0.3 on 2024-04-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saasapp", "0005_alter_modulemapping_tenant"),
        ("tenant", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientfeedback",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="toolfeedback",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
        ),
    ]
