# Generated by Django 5.0.3 on 2024-04-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillstockhistory",
            name="machine_id_store",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
