# Generated by Django 5.0.3 on 2024-04-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_refillstockhistory_machine_id_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refillstockhistory",
            name="machine",
        ),
    ]
