# Generated by Django 5.0.3 on 2024-04-06 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_remove_refillstockhistory_machine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refillstockhistory",
            name="refill_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="refillstockhistory",
            name="stock_after_refill",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="refillstockhistory",
            name="stock_before_refill",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
