# Generated by Django 5.0.3 on 2024-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0005_user_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
