# Generated by Django 5.0.3 on 2024-05-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0006_user_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_host", models.CharField(blank=True, max_length=100, null=True)),
                ("email_port", models.IntegerField(blank=True, null=True)),
                (
                    "email_host_user",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_host_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=True, verbose_name="Use TLS"),
                ),
                (
                    "email_fail_silently",
                    models.BooleanField(default=False, verbose_name="Fail Silently"),
                ),
            ],
        ),
    ]
