# Generated by Django 5.0.1 on 2024-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_customemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemail',
            name='default_from_email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customemail',
            name='use_ssl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customemail',
            name='email_fail_silently',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customemail',
            name='email_use_tls',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
