# Generated by Django 5.0.3 on 2024-06-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_customemail_default_from_email_customemail_use_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rolename',
            field=models.CharField(blank=True, default='User', max_length=100, null=True),
        ),
    ]
