# Generated by Django 5.0.3 on 2024-06-07 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_user_rolename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(related_name='userscreate', to=settings.AUTH_USER_MODEL),
        ),
    ]
