# Generated by Django 5.0.6 on 2024-06-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0014_role_permissions_alter_module_role_alter_role_users'),
        ('userapp', '0009_user_rolename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machinedataapp.custompermission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machinedataapp.role'),
        ),
    ]
