# Generated by Django 5.0.6 on 2024-06-07 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_user_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='userscreate', to=settings.AUTH_USER_MODEL),
        ),
    ]
