# Generated by Django 5.0.6 on 2024-06-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_user_custom_permissions'),
        ('userapp', '0011_remove_user_custom_permissions_user_permissions_and_more'),
    ]

    operations = [
    ]
