# Generated by Django 5.0.6 on 2024-06-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_merge_20240607_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custom_permissions',
        ),
    ]
