# Generated by Django 5.0.3 on 2024-06-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0015_module_submodules_submodule_permissions_and_more'),
        ('userapp', '0012_remove_user_rolename_user_rolesname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='custompermission_users_permission', to='machinedataapp.custompermission'),
        ),
    ]
