# Generated by Django 5.0.3 on 2024-06-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0016_remove_custompermission_submodule_remove_module_role_and_more'),
        ('userapp', '0013_remove_user_permissions_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='custompermission_users_permission', to='machinedataapp.custompermission'),
        ),
    ]
