# Generated by Django 5.0.3 on 2024-04-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machinedataapp", "0001_initial"),
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinemaster",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant",
                to="tenant.tenant",
            ),
        ),
    ]
