# Generated by Django 5.0.3 on 2024-04-06 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machinedataapp", "0002_initial"),
        ("tenant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="machineusermapping",
            name="assigned_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="machineusermapping",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="machineusermapping",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="machinedataapp.machinemaster",
            ),
        ),
        migrations.AddField(
            model_name="machinemaster",
            name="model_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelcapacity",
                to="machinedataapp.modelcapacity",
            ),
        ),
        migrations.AddField(
            model_name="machinemaster",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="machinedataapp.product",
            ),
        ),
        migrations.AddField(
            model_name="machinemaster",
            name="rqcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="machinedataapp.qrcode",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
            ),
        ),
    ]
