# Generated by Django 5.0.3 on 2024-04-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machinedataapp", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.FileField(
                blank=True, default="favicon.ico", null=True, upload_to="favicons/"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.FileField(
                blank=True, default="favicon.jpg", null=True, upload_to="logos/"
            ),
        ),
    ]
