# Generated by Django 5.0.3 on 2024-04-30 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machinedataapp", "0004_alter_sitesettings_favicon_alter_sitesettings_logo"),
        ("tenant", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True, default="favicon.ico", null=True, upload_to="favicons/"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True, default="favicon.jpg", null=True, upload_to="logos/"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
            ),
        ),
    ]
