# Generated by Django 5.0.3 on 2024-05-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0006_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticsrno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
