# Generated by Django 5.0.3 on 2024-05-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0008_alter_ticket_priority_alter_ticket_problem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='machine_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machinedataapp.machinemaster'),
        ),
    ]
