# Generated by Django 5.0.3 on 2024-06-06 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0012_excelfile_module_role_rolemoduleassignment_submodule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='machinedataapp.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolemoduleassignment',
            name='sub_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='machinedataapp.submodule'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='codename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='machinedataapp.submodule'),
        ),
        migrations.AlterField(
            model_name='rolemoduleassignment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='machinedataapp.module'),
        ),
        migrations.AlterField(
            model_name='rolemoduleassignment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_modules', to='machinedataapp.role'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='machinedataapp.module'),
        ),
        migrations.DeleteModel(
            name='RoleSubModuleAssignment',
        ),
    ]
