# Generated by Django 5.0.3 on 2024-06-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinedataapp', '0014_role_permissions_alter_module_role_alter_role_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='submodules',
            field=models.ManyToManyField(blank=True, related_name='module_list_submodules', to='machinedataapp.submodule'),
        ),
        migrations.AddField(
            model_name='submodule',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='submodule_list_permissions', to='machinedataapp.custompermission'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='machinedataapp.submodule'),
        ),
        migrations.AlterField(
            model_name='module',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_list', to='machinedataapp.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='role_permissions', to='machinedataapp.custompermission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodule_list', to='machinedataapp.module'),
        ),
    ]
